-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJRZJLEX+DS8KRjt3
b/NOZqe7/bmYRVoqU5nGR0UQTRugCgYIKoZIzj0DAQehRANCAAStMy0jRJu1+VZQ
0cKKJBB3WSmDJDkrFEjXcOjEBDqUzbVGt3ZwNe3usaDg1ZOnwUZn6/lEfs3osqDY
NgJOvB8i
-----END PRIVATE KEY-----